name: auri_app
description: "Auri â€” asistente personal inteligente"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.10

  cupertino_icons: ^1.0.8
  rive: ^0.13.20

  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.0

  uuid: ^4.4.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  dio: ^5.4.0

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  geolocator: ^12.0.0
  geocoding: ^3.0.0

  flutter_sound: ^9.2.13

  web_socket_channel: ^2.4.0

  flutter_tts: ^3.6.3
  just_audio: ^0.9.40
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/google/service_account.json
    - .env
